dist: trusty
sudo: false

addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "6.9"
cache:
  directories: node_modules

branches:
  only: master

before_install:
  - if [[ `npm -v` != 4* ]]; then npm i -g npm@4; fi

before_script:
  - "export CHROME_BIN=$(which google-chrome)"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI

script: npm run test:ci

after_script: npm run test:ci:coveralls